# Generated by Django 3.1.12 on 2021-06-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese',
            name='slug',
        ),
    ]
