# Generated by Django 3.1.12 on 2021-06-24 15:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_remove_cheese_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='name', unique=True, verbose_name='Cheese Adress'),
            preserve_default=False,
        ),
    ]
